config/routes.rb
Rails.application.routes.draw do

root 'landing#index'

get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
get '/logout' => 'sessions#destroy'

get '/signup' => 'users#new'
post '/users' => 'users#create'

get "age", to: "topics#age"
get "agefilter", to: "topics#agefilter"

resources :helps
resources :supports

  resources :topics do
    resources :articles
    resources :stories
    resources :resources do
      resources :reviews, shallow: true
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :topic

  validates :author, presence: true
  validates :email, presence: true
  validates :body, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @topic = Topic.find(params[:topic_id])
    @articles = Article.where(topic_id: params[:topic_id])
    @articles = @articles.sort { |a,b| b.updated_at <=> a.updated_at }
    render :index
  end

  def new
    @topic = Topic.find(params[:topic_id])
  end

  def edit
    @article = Article.find(params[:id])
    @topic = Topic.find(params[:topic_id])
  end

  def update
    @article = Article.find(params[:id])
    @article.topic_id = params[:topic_id]
    if @article.update(edit_article_params)
      redirect_to topic_articles_path(@article.topic_id)
    else
      render :edit
    end
  end

  def create
      @article = Article.new(new_article_params)
      @article.topic_id = params[:topic_id]
      if @article.save
        redirect_to topic_articles_path(@article.topic_id)
      else
        render :new
      end
  end

  def destroy
    @article = Article.find(params[:id])
    @topic = Topic.find(params[:topic_id])
    @article.destroy
    redirect_to topic_articles_path(@topic.id)
  end

  private
  def new_article_params
    params.require(:articles).permit(:author, :email, :body)
  end

  def edit_article_params
    params.require(:article).permit(:author, :email, :body)
  end

end

app/views/articles/edit.html.erb
<div class = "edit-article-form">
  <ul class="errors">
    <% if @article %>
      <% @article.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    <% end %>
  </ul>
<div class = "fields new_article">
  <h3>Edit article</h3>
  <%= form_for @article, url: topic_article_path do |f| %>
    <p>
      <%= f.label :author %>
      <%= f.text_field :author, value: @article.author, size: "24" %>
    </p>
    <p>
      <%= f.label :email %>
      <%= f.text_area :email, value: @article.email, size: "40" %>
    </p>
    <p>
      <%= f.label :summary %>
      <%= f.text_area :body, value: @article.body, size: "40x20" %>
    </p>
      <%= f.submit "Submit", class: "button" %>
  <% end %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="topics_list two">
  <h3>WHAT EXPERTS SAY ABOUT <%= @topic.name.upcase %></h3>
  <% if current_user %>
  <%= button_to "add an expert summary", new_topic_article_path, method: "get" , class: "button" %>
    <% end %>
  <% @articles.each do |article| %>
  <h5 class ="topic"><%= simple_format(article.body) %></h5>
  <h5 class ="topic">-<%= article.author %><span class="italic"> -- updated: <%= article.updated_at.strftime("%B %d, %Y") %> </span></h5>
    <% if current_user %>
      <div class="container">
        <%= button_to "edit", edit_topic_article_path(@topic, article), method: "get", class: "button" %>
        <%= button_to "delete", topic_article_path(@topic, article), method: "delete", class: "button",data: {confirm: "Are you sure? (this action can not be undone)"} %>
      </div>
    <% end %>
  <% end %>

</div>

app/views/articles/new.html.erb
<div class = "new-article-form">
  <ul class="errors">
    <% if @article %>
      <% @article.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    <% end %>
  </ul>
<div class = "fields new_article">
  <h3>New article about <%= @topic.name.capitalize %></h3>
  <%= form_for :articles, url: topic_articles_path do |f| %>
    <p>
      <%= f.label :author %>
      <%= f.text_field :author, size: "35", placeholder: "*display name" %>
    </p>
    <p>
      <%= f.label :email %>
      <%= f.text_field :email , size: "35", placeholder: "*not displayed" %>
    </p>
    <p>
      <%= f.label :summary %>
      <%= f.text_area :body , size: "34x6", placeholder: "summary" %>
    </p>
      <%= f.submit "Submit", class: "button" %>
  <% end %>
  </div>
</div>