config/routes.rb
Rails.application.routes.draw do

root 'landing#index'

get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
get '/logout' => 'sessions#destroy'

get '/signup' => 'users#new'
post '/users' => 'users#create'

get "age", to: "topics#age"
get "agefilter", to: "topics#agefilter"

resources :helps
resources :supports

  resources :topics do
    resources :articles
    resources :stories
    resources :resources do
      resources :reviews, shallow: true
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_many :stories, dependent: :destroy
  has_many :resources, dependent: :destroy

  validates :name, presence: true
  validates :summary, presence: true

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all
    @topics = @topics.sort { |a,b| a.name.downcase <=> b.name.downcase }
    render :index
  end

  def age
    render :ages
  end

  def agefilter
    @topics = Topic.where(min_age: [params[:ages][:min_age]..params[:ages][:max_age]])
    render :index
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update(edit_topic_params)
      redirect_to topics_path
    else
      render :edit
    end
  end

  def create
      @topic = Topic.new(topic_params)
      if @topic.save
        redirect_to topics_path
      else
        render :new
      end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_path
  end

  private
  def topic_params
    params.require(:topics).permit(:name, :summary, :min_age, :max_age)
  end

  def edit_topic_params
    params.require(:topic).permit(:name, :summary, :min_age, :max_age)
  end
end

app/views/topics/ages.html.erb
<div class="topics_list two">
  <h1>AGE RANGES</h1>
  <h3 class ="topic"><%= link_to "0-3 MONTHS", agefilter_path(:ages => { min_age: 0, max_age: 3 }) %></h3>
  <h3 class ="topic"><%= link_to "4-6 MONTHS", agefilter_path(:ages => { min_age: 4, max_age: 6 }) %></h3>
  <h3 class ="topic"><%= link_to "7-12 MONTHS", agefilter_path(:ages => { min_age: 7, max_age: 12 }) %></h3>
  <h3 class ="topic"><%= link_to "13-18 MONTHS", agefilter_path(:ages => { min_age: 13, max_age: 18 }) %></h3>
  <h3 class ="topic"><%= link_to "19-36 MONTHS", agefilter_path(:ages => { min_age: 19, max_age: 36 }) %></h3>
  <h3 class ="topic"><%= link_to "37+ MONTHS", agefilter_path(:ages => { min_age: 37, max_age: 90 }) %></h3>
</div>

app/views/topics/edit.html.erb
<div class = "edit-topic-form">
  <ul class="errors">
    <% if @topic %>
      <% @topic.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    <% end %>
  </ul>
<div class = "fields">
  <%= form_for @topic, url: topic_path do |f| %>
    <p>
      <%= f.label :name %>
      <%= f.text_area :name , size: "40", value: @topic.name %>
    </p>
    <p>
      <%= f.label :summary %>
      <%= f.text_area :summary , size: "40x20", value: @topic.summary %>
    </p>
    <p>
      <%= f.label :min_age %>
      <%= f.text_field :min_age , size: "20", value: @topic.min_age %>
    </p>
    <p>
      <%= f.label :max_age %>
      <%= f.text_field :max_age , size: "20", value: @topic.max_age %>
    </p>
      <%= f.submit "Submit", class: "button" %>
  <% end %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topics_list two">
  <h1>TOPICS</h1>
  <% if current_user %>
  <%= button_to "add a topic", new_topic_path, method: "get" , class: "button" %>
    <% end %>
  <% @topics.each do |topic| %>
      <h3 class ="topic"><%=link_to topic.name.capitalize, topic_path(topic.id) %></h3>
      <% if current_user %>
            <div class="container">
        <%= button_to "edit", edit_topic_path(topic), method: "get", class: "button" %>
        <%= button_to "delete", topic_path(topic), method: "delete", class: "button",data: {confirm: "Are you sure? (this will also delete all associated articles, stories, and resources, and can not be undone)"} %>
        </div>
      <% end %>
    <% end %>
</div>

app/views/topics/new.html.erb
<div class = "new-topic-form">
  <ul class="errors">
    <% if @topic %>
      <% @topic.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    <% end %>
  </ul>
<div class = "fields">
  <%= form_for :topics, url: topics_path do |f| %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name , size: "35", placeholder: "new topic name" %>
    </p>
    <p>
      <%= f.label :summary %>
      <%= f.text_area :summary , size: "34x10", placeholder: "topic summary" %>
    </p>
    <p>
      <%= f.label :min_age %>
      <%= f.text_field :min_age , size: "35", placeholder: "age range start" %>
    </p>
    <p>
      <%= f.label :max_age %>
      <%= f.text_field :max_age , size: "35", placeholder: "age range end" %>
    </p>
      <%= f.submit "Submit", class: "button" %>
  <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<div class="topic two">
  <h3 class="heading">AGE: <%=@topic.min_age%>-<%=@topic.max_age%> Months</h3>
    <h1><%=@topic.name.upcase %></h1>
  <h3 class="heading">DEFINITION:</h3>
    <%= simple_format(@topic.summary) %>

  <div class="show-buttons-container">
    <a href="/topics/<%= @topic.id %>/articles">
    <div class="container">
      <div class="circle orange">
        <div class="btn-text">
          WHAT EXPERTS SAY
        </div>
      </div>
    </div>
    </a>
    <a href="/topics/<%= @topic.id %>/stories">
    <div class="container">
      <div class="circle grey">
        <div class="btn-text">
          PARENT STORIES
        </div>
      </div>
    </div>
    </a>
    <a href="/topics/<%= @topic.id %>/resources">
    <div class="container">
      <div class="circle orange">
        <div class="btn-text">
          LOCAL RESOURCES
        </div>
      </div>
    </div>
    </a>
  </div>
  <% if current_user %>
    <div class="container">
      <%= button_to "edit", edit_topic_path(@topic), method: "get", class: "button" %>
      <%= button_to "delete", topic_path(@topic), method: "delete", class: "button",data: {confirm: "Are you sure? (this will also delete all associated articles, stories, and resources, and can not be undone)"} %>
    </div>
  <% end %>
</div>