config/routes.rb
Rails.application.routes.draw do

root 'landing#index'

get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
get '/logout' => 'sessions#destroy'

get '/signup' => 'users#new'
post '/users' => 'users#create'

get "age", to: "topics#age"
get "agefilter", to: "topics#agefilter"

resources :helps
resources :supports

  resources :topics do
    resources :articles
    resources :stories
    resources :resources do
      resources :reviews, shallow: true
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/resources/edit.html.erb
<div class = "edit-resource-form">
  <ul class="errors">
    <% if @resource %>
      <% @resource.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    <% end %>
  </ul>
<div class = "fields new_resource">
  <h3>Edit resource</h3>
  <%= form_for @resource, url: topic_resource_path do |f| %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name, size: "35", value: @resource.url %>
    </p>
    <p>
      <%= f.label :'website (url)' %>
      <%= f.text_field :url, size: "35", value: @resource.url %>
    </p>
    <p>
      <%= f.label :email %>
      <%= f.text_field :email , size: "35", value: @resource.email %>
    </p>
    <p>
      <%= f.label :phone %>
      <%= f.text_field :phone , size: "35", value: @resource.phone %>
    </p>
    <p>
      <%= f.label :address %>
      <%= f.text_field :address , size: "35", value: @resource.address %>
    </p>
    <p>
      <%= f.label :'zip code' %>
      <%= f.text_field :zip_code , size: "35", value: @resource.zip_code %>
    </p>
    <p>
      <%= f.label :summary %>
      <%= f.text_area :summary , size: "34x6", value: @resource.summary %>
    </p>
      <%= f.submit "Submit", class: "button" %>
  <% end %>
  </div>
</div>

app/views/resources/index.html.erb
<div class="topics_list two">
  <h3><%= @topic.name.upcase %> RESOURCES</h3>
  <% if current_user %>
  <%= button_to "add a resource", new_topic_resource_path, method: "get", class: "button" %>
    <% end %>
  <% @resources.each do |resource| %>
  <h5 class="topic"><%=resource.name%><span class="italic"> -- updated: <%= resource.updated_at.strftime("%B %d, %Y") %> </span></h5>
  <h5 class ="topic"><%= simple_format(resource.summary) %></h5>
  <p class ="topic"><a href="http://<%=resource.url%>"><%=resource.url%></a> | <%=resource.phone %> | <a href="mailto:<%=resource.email%>"><%=resource.email %></a></p>
  <p class ="topic"><%=resource.address %> | <%=resource.zip_code %> | reviews: <%=resource.reviews.count %>| <span class ="topic"><%=link_to "read reviews", topic_resource_reviews_path(@topic.id, resource.id) %></span></p>
</br>
  <%= button_to "review", new_topic_resource_review_path(@topic, resource), method: "get", class: "button" %>

  <% if current_user %>
    <div class="container">
      <%= button_to "edit", edit_topic_resource_path(@topic, resource), method: "get", class: "button" %>
      <%= button_to "delete", topic_resource_path(@topic, resource), method: "delete", class: "button",data: {confirm: "Are you sure? (this action can not be undone)"} %>
    </div>
  <% end %>
<% end %>
</div>

app/views/resources/new.html.erb
<div class = "new-resource-form">
  <ul class="errors">
    <% if @resource %>
      <% @resource.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    <% end %>
  </ul>
<div class = "fields new_resource">
  <h3>New <%= @topic.name.capitalize %> resource</h3>
  <%= form_for :resources, url: topic_resources_path do |f| %>
    <p>
      <%= f.label :'name' %>
      <%= f.text_field :name, size: "35", placeholder: "company/organization name" %>
    </p>
    <p>
      <%= f.label :'website (url)' %>
      <%= f.text_field :url, size: "35", placeholder: "resource website" %>
    </p>
    <p>
      <%= f.label :email %>
      <%= f.text_field :email , size: "35", placeholder: "contact email" %>
    </p>
    <p>
      <%= f.label :phone %>
      <%= f.text_field :phone , size: "35", placeholder: "contact phone" %>
    </p>
    <p>
      <%= f.label :address %>
      <%= f.text_field :address , size: "35", placeholder: "physical address" %>
    </p>
    <p>
      <%= f.label :'zip code' %>
      <%= f.text_field :zip_code , size: "35", placeholder: "zip code" %>
    </p>
    <p>
      <%= f.label :summary %>
      <%= f.text_area :summary , size: "34x6", placeholder: "summary" %>
    </p>
      <%= f.submit "Submit", class: "button" %>
  <% end %>
  </div>
</div>