config/routes.rb
Rails.application.routes.draw do

root 'landing#index'

get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
get '/logout' => 'sessions#destroy'

get '/signup' => 'users#new'
post '/users' => 'users#create'

get "age", to: "topics#age"
get "agefilter", to: "topics#agefilter"

resources :helps
resources :supports

  resources :topics do
    resources :articles
    resources :stories
    resources :resources do
      resources :reviews, shallow: true
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

def index
  @reviews = Review.where(resource_id: params[:resource_id])
  @resource = Resource.find(params[:resource_id])
  render :index
end

def new
end

def edit
  @review = Review.find(params[:id])
end

def update
  @review = Resource.find(params[:id])
  if @review.update(edit_review_params)
    redirect_to topic_reviews_path(@review.topic_id)
  else
    render :edit
  end
end

def create
  @review = Review.new(review_params)
  @topic = Topic.find(params[:topic_id])
  @resource = Resource.find(params[:resource_id])
  @review.resource_id = params[:resource_id]
  if verify_recaptcha(model: @review) && @review.save
    redirect_to topic_resources_path(@topic, @resource)
  else
    render :new
  end
end

def destroy
  @review = Review.find(params[:id])
  @resource = Resource.find(params[:resource_id])
  @review.destroy
  redirect_to topic_resources_path(@resource.id)
end

private
def review_params
  params.require(:reviews).permit(:author, :stars, :body, :email)
end
def edit_review_params
  params.require(:reviews).permit(:author, :stars, :body, :email)
end
end

app/views/reviews/edit.html.erb
<div class = "edit-review-form">
  <ul class="errors">
    <% if @review %>
      <% @review.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    <% end %>
  </ul>
<div class = "fields">
  <%= form_for @review, url: review_path do |f| %>
    <p>
      <%= f.label :author %>
      <%= f.text_field :author, size: "35", value: @review.author %>
    </p>
    <p>
      <%= f.label :review %>
      <%= f.text_area :body , size: "34x6", value: @review.body %>
    </p>
    <p>
      <%= f.label :'stars (out of five)' %>
      <%= f.select(:stars, 1..5), value: @review.stars %>
    </p>
    <p>
      <%= f.label :email %>
      <%= f.text_field :email , size: "35", @review.email %>
    </p>
      <%= recaptcha_tags %>
      <%= f.submit "Submit", class: "button" %>
  <% end %>
  </div>
</div>

app/views/reviews/index.html.erb
<div class="topics_list two">
  <h3><%= @resource.name.upcase %> REVIEWS</h3>
    <%= button_to "review", new_topic_resource_review_path(@resource.topic_id, @resource), method: "get", class: "button" %>
  <% @reviews.each do |review| %>
  <p class ="topic"><%=review.stars %> STARS (out of 5)</p>
  <p class ="topic"><%= simple_format(review.body) %>
  <p class ="topic"><%=review.author %></p><br />
  <% if current_user %>
    <div class="container">
      <%= button_to "edit", edit_review_path(@review), method: "get", class: "button" %>
      <%= button_to "delete", review_path(@review), method: "delete", class: "button",data: {confirm: "Are you sure? (this action can not be undone)"} %>
    </div>
  <% end %>
<% end %>
</div>

app/views/reviews/new.html.erb
<div class = "new-review-form">
  <ul class="errors">
    <% if @review %>
      <% @review.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    <% end %>
  </ul>
<div class = "fields">
  <%= form_for :reviews, url: topic_resource_reviews_path do |f| %>
    <p>
      <%= f.label :author %>
      <%= f.text_field :author, size: "35", placeholder: "*display name" %>
    </p>
    <p>
      <%= f.label :review %>
      <%= f.text_area :body , size: "34x6", placeholder: "your review here" %>
    </p>
    <p>
      <%= f.label :'stars (out of five)' %>
      <%= f.select(:stars, 1..5) %>
    </p>
    <p>
      <%= f.label :email %>
      <%= f.text_field :email , size: "35", placeholder: "*not displayed" %>
    </p>
      <%= recaptcha_tags %>
      <%= f.submit "Submit", class: "button" %>
  <% end %>
  </div>
</div>